---
title: "K-Nearest Neighbours"
output: html_document
---

### We will be using the iris data set for this example.

```{r}
data("iris")
head(iris)
str(iris)
```

### Let's split the iris dataset into training and test set

```{r}
train_index_knearest_iris <- sample(1:nrow(iris), 0.7*nrow(iris))
train_knearest_iris <-iris[train_index_knearest_iris,]
test_knearest_iris <- iris[-train_index_knearest_iris,]

```
### Now, we remove the Species column from our training and test datasets.


```{r}
train_knearest_iris_newset <- train_knearest_iris[,-5]

test_knearest_iris_newset <- test_knearest_iris[,-5]

```
### Now, we store the labels from our training and test datasets

```{r}
iris_train_labels <- train_knearest_iris$Species

iris_test_labels <- test_knearest_iris$Species

```
### For k=3, let's make our prediction on the test set.

```{r}
#install.packages("ISLR")

#install.packages("class")
library(class)

iris_knn_prediction <- knn(train=train_knearest_iris_newset, test = test_knearest_iris_newset , cl=iris_train_labels, k=3)


```
### Let's see the confusion matrix.
```{r}

#install.packages("gmodels")
library(gmodels)

CrossTable(x=iris_test_labels, y= iris_knn_prediction, prop.chisq=FALSE)

```

For k=11, let's make our prediction on the test set.


```{r}
library(class)
iris_knn_prediction_11 <- knn(train=train_knearest_iris_newset, test=test_knearest_iris_newset, cl=iris_train_labels , k=11)

library(gmodels)
CrossTable(x=iris_test_labels , y=iris_knn_prediction , prop.chisq = FALSE)
```

